// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/event.proto

#include "event.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace event {
PROTOBUF_CONSTEXPR Event::Event(::_pbi::ConstantInitialized): _impl_{
    decltype(_impl_.event_id_){&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , decltype(_impl_.user_id_){&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , decltype(_impl_.platform_){&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , decltype(_impl_.event_type_){&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , decltype(_impl_.payload_){&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , decltype(_impl_.ts_){int64_t{0}}
  , decltype(_impl_._cached_size_){}} {}
struct EventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDefaultTypeInternal() {}
  union { Event _instance; };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDefaultTypeInternal _Event_default_instance_;
}

static ::_pb::Metadata file_level_metadata_proto_2fevent_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2fevent_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fevent_2eproto = nullptr;

const uint32_t TableStruct_proto_2fevent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u, PROTOBUF_FIELD_OFFSET(::event::Event, _internal_metadata_),
  ~0u, ~0u, ~0u, ~0u,
  PROTOBUF_FIELD_OFFSET(::event::Event, _impl_.event_id_),
  PROTOBUF_FIELD_OFFSET(::event::Event, _impl_.user_id_),
  PROTOBUF_FIELD_OFFSET(::event::Event, _impl_.platform_),
  PROTOBUF_FIELD_OFFSET(::event::Event, _impl_.event_type_),
  PROTOBUF_FIELD_OFFSET(::event::Event, _impl_.ts_),
  PROTOBUF_FIELD_OFFSET(::event::Event, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::event::Event)},
};
static const ::_pb::Message* const file_default_instances[] = {
  &::event::_Event_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fevent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021proto/event.proto\022\005event\"m\n\005Event\022\020\n\010event_id\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\t\022\020\n\010platform\030\003 \001(\t\022\022\n\nevent_type\030\004 \001(\t\022\n\n\002ts\030\005 \001(\003\022\017\n\007payload\030\006 \001(\014b\006proto3";
static ::_pbi::once_flag descriptor_table_proto_2fevent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fevent_2eproto = {
    false, false, 145, descriptor_table_protodef_proto_2fevent_2eproto,
    "proto/event.proto", &descriptor_table_proto_2fevent_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_proto_2fevent_2eproto::offsets,
    file_level_metadata_proto_2fevent_2eproto, file_level_enum_descriptors_proto_2fevent_2eproto,
    file_level_service_descriptors_proto_2fevent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fevent_2eproto_getter() {
  return &descriptor_table_proto_2fevent_2eproto;
}
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fevent_2eproto(&descriptor_table_proto_2fevent_2eproto);
namespace event {

class Event::_Internal {};

Event::Event(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
}
Event::Event(const Event& from) : ::PROTOBUF_NAMESPACE_ID::Message() {
  Event* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.event_id_){}, decltype(_impl_.user_id_){},
      decltype(_impl_.platform_){}, decltype(_impl_.event_type_){},
      decltype(_impl_.payload_){}, decltype(_impl_.ts_){},
      decltype(_impl_._cached_size_){}};
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.event_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.event_id_.Set("", GetArenaForAllocation());
  #endif
  if (!from._internal_event_id().empty()) {
    _this->_impl_.event_id_.Set(from._internal_event_id(), _this->GetArenaForAllocation());
  }
  _impl_.user_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_id_.Set("", GetArenaForAllocation());
  #endif
  if (!from._internal_user_id().empty()) {
    _this->_impl_.user_id_.Set(from._internal_user_id(), _this->GetArenaForAllocation());
  }
  _impl_.platform_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.platform_.Set("", GetArenaForAllocation());
  #endif
  if (!from._internal_platform().empty()) {
    _this->_impl_.platform_.Set(from._internal_platform(), _this->GetArenaForAllocation());
  }
  _impl_.event_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.event_type_.Set("", GetArenaForAllocation());
  #endif
  if (!from._internal_event_type().empty()) {
    _this->_impl_.event_type_.Set(from._internal_event_type(), _this->GetArenaForAllocation());
  }
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif
  if (!from._internal_payload().empty()) {
    _this->_impl_.payload_.Set(from._internal_payload(), _this->GetArenaForAllocation());
  }
  _this->_impl_.ts_ = from._impl_.ts_;
}

inline void Event::SharedCtor(::_pb::Arena* arena, bool is_message_owned) {
  (void)arena; (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.event_id_){}, decltype(_impl_.user_id_){},
      decltype(_impl_.platform_){}, decltype(_impl_.event_type_){},
      decltype(_impl_.payload_){}, decltype(_impl_.ts_){int64_t{0}},
      decltype(_impl_._cached_size_){}};
  _impl_.event_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.event_id_.Set("", GetArenaForAllocation());
  #endif
  _impl_.user_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_id_.Set("", GetArenaForAllocation());
  #endif
  _impl_.platform_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.platform_.Set("", GetArenaForAllocation());
  #endif
  _impl_.event_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.event_type_.Set("", GetArenaForAllocation());
  #endif
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif
}

Event::~Event() {
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
    (void)arena;
    return;
  }
  SharedDtor();
}
inline void Event::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.event_id_.Destroy();
  _impl_.user_id_.Destroy();
  _impl_.platform_.Destroy();
  _impl_.event_type_.Destroy();
  _impl_.payload_.Destroy();
}

void Event::Clear() {
  uint32_t cached_has_bits = 0; (void) cached_has_bits;
  _impl_.event_id_.ClearToEmpty();
  _impl_.user_id_.ClearToEmpty();
  _impl_.platform_.ClearToEmpty();
  _impl_.event_type_.ClearToEmpty();
  _impl_.payload_.ClearToEmpty();
  _impl_.ts_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Event::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag; ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      case 1: {
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_event_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr); CHK_(::_pbi::VerifyUTF8(str, "event.Event.event_id"));
        } else goto handle_unusual; continue;
      }
      case 2: {
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_user_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr); CHK_(::_pbi::VerifyUTF8(str, "event.Event.user_id"));
        } else goto handle_unusual; continue;
      }
      case 3: {
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_platform();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr); CHK_(::_pbi::VerifyUTF8(str, "event.Event.platform"));
        } else goto handle_unusual; continue;
      }
      case 4: {
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_event_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr); CHK_(::_pbi::VerifyUTF8(str, "event.Event.event_type"));
        } else goto handle_unusual; continue;
      }
      case 5: {
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.ts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual; continue;
      }
      case 6: {
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_payload();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual; continue;
      }
      default: goto handle_unusual;
    }
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr); ctx->SetLastTag(tag); goto message_done;
    }
    ptr = UnknownFieldParse(tag, _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(), ptr, ctx);
    CHK_(ptr != nullptr);
  }
message_done:
  return ptr;
failure:
  ptr = nullptr; goto message_done;
#undef CHK_
}

uint8_t* Event::_InternalSerialize(uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  uint32_t cached_has_bits = 0; (void) cached_has_bits;

  if (!this->_internal_event_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_event_id().data(), static_cast<int>(this->_internal_event_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "event.Event.event_id");
    target = stream->WriteStringMaybeAliased(1, this->_internal_event_id(), target);
  }
  if (!this->_internal_user_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user_id().data(), static_cast<int>(this->_internal_user_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "event.Event.user_id");
    target = stream->WriteStringMaybeAliased(2, this->_internal_user_id(), target);
  }
  if (!this->_internal_platform().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_platform().data(), static_cast<int>(this->_internal_platform().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "event.Event.platform");
    target = stream->WriteStringMaybeAliased(3, this->_internal_platform(), target);
  }
  if (!this->_internal_event_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_event_type().data(), static_cast<int>(this->_internal_event_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "event.Event.event_type");
    target = stream->WriteStringMaybeAliased(4, this->_internal_event_type(), target);
  }
  if (this->_internal_ts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_ts(), target);
  }
  if (!this->_internal_payload().empty()) {
    target = stream->WriteBytesMaybeAliased(6, this->_internal_payload(), target);
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  return target;
}

size_t Event::ByteSizeLong() const {
  size_t total_size = 0;
  uint32_t cached_has_bits = 0; (void) cached_has_bits;
  if (!this->_internal_event_id().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(this->_internal_event_id());
  }
  if (!this->_internal_user_id().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(this->_internal_user_id());
  }
  if (!this->_internal_platform().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(this->_internal_platform());
  }
  if (!this->_internal_event_type().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(this->_internal_event_type());
  }
  if (!this->_internal_payload().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(this->_internal_payload());
  }
  if (this->_internal_ts() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_ts());
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Event::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck, Event::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData* Event::GetClassData() const { return &_class_data_; }

void Event::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Event*>(&to_msg);
  auto& from = static_cast<const Event&>(from_msg);
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0; (void) cached_has_bits;
  if (!from._internal_event_id().empty()) { _this->_internal_set_event_id(from._internal_event_id()); }
  if (!from._internal_user_id().empty()) { _this->_internal_set_user_id(from._internal_user_id()); }
  if (!from._internal_platform().empty()) { _this->_internal_set_platform(from._internal_platform()); }
  if (!from._internal_event_type().empty()) { _this->_internal_set_event_type(from._internal_event_type()); }
  if (!from._internal_payload().empty()) { _this->_internal_set_payload(from._internal_payload()); }
  if (from._internal_ts() != 0) { _this->_internal_set_ts(from._internal_ts()); }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Event::CopyFrom(const Event& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Event::IsInitialized() const { return true; }

void Event::InternalSwap(Event* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(&_impl_.event_id_, lhs_arena, &other->_impl_.event_id_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(&_impl_.user_id_, lhs_arena, &other->_impl_.user_id_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(&_impl_.platform_, lhs_arena, &other->_impl_.platform_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(&_impl_.event_type_, lhs_arena, &other->_impl_.event_type_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(&_impl_.payload_, lhs_arena, &other->_impl_.payload_, rhs_arena);
  swap(_impl_.ts_, other->_impl_.ts_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Event::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fevent_2eproto_getter, &descriptor_table_proto_2fevent_2eproto_once,
      file_level_metadata_proto_2fevent_2eproto[0]);
}

}  // namespace event
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::event::Event*
Arena::CreateMaybeMessage< ::event::Event >(Arena* arena) {
  return Arena::CreateMessageInternal< ::event::Event >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
#include <google/protobuf/port_undef.inc>
